### 매장 좋아요 등록 및 취소
POST http://localhost:8080/api/v1/users/liked/stores/6
Authorization: {{user1Auth}}

### 매장 좋아요 등록 및 취소 (존재하지 않는 매장)
POST http://localhost:8080/api/v1/users/liked/stores/100
Authorization: {{user1Auth}}

---

### 리뷰 좋아요 등록 및 취소
POST http://localhost:8080/api/v1/users/liked/reviews/1
Authorization: {{user2Auth}}

### 리뷰 좋아요 등록 및 취소 (존재하지 않는 리뷰)
POST http://localhost:8080/api/v1/users/liked/reviews/1000
Authorization: {{user2Auth}}

### 리뷰 좋아요 등록 및 취소 (자신의 리뷰)
POST http://localhost:8080/api/v1/users/liked/reviews/1
Authorization: {{user1Auth}}

---

### 좋아요한 매장 전체 조회
GET http://localhost:8080/api/v1/users/liked/stores
Authorization: {{user1Auth}}

### 좋아요한 매장 전체 조회 (매장 이름 순 정렬)
GET http://localhost:8080/api/v1/users/liked/stores?sortBy=storename
Authorization: {{user1Auth}}

### 좋아요한 매장 전체 조회 (매장 이름 순 정렬)
GET http://localhost:8080/api/v1/users/liked/stores?sortBy=storename&isDesc=false
Authorization: {{user1Auth}}

### 좋아요한 매장 전체 조회 (최소주문금액 필터) -> 최소주문금액이 16000원 이하인 매장만 조회
GET http://localhost:8080/api/v1/users/liked/stores?minTotalPriceLoe=16000
Authorization: {{user1Auth}}

### 좋아요한 매장 전체 조회 (최소주문금액 필터) -> 최소주문금액이 16000원 이상인 매장만 조회
GET http://localhost:8080/api/v1/users/liked/stores?minTotalPriceGoe=16000
Authorization: {{user1Auth}}

---

### 좋아요한 유저 리뷰 전체 조회
GET http://localhost:8080/api/v1/users/liked/userReviews
Authorization: {{user2Auth}}